### PR TITLE
Fix query get old FPMMTrade

### LINKED ISSUE #39: Wrong old odds on sell/buy on market notification
The old odds from a market sell or buy notification is getting wrong from the subgraph.

Fix: Add a query for the old records from the same market id.

### PR DESCRIPTION
**Pull request by girianshido**
- Add `fpmmId` and `creationTimestamp` to getOldTrade query to find the
old trades before the current trade and get the right outcomeTokenMarginalPrices.
- Remove Promise.all and then from `findTradeEvents` event.

Resolves: #39

### CODE REVIEW

File: src/events/tradeEvents.js [hunk 1]
```diff
@@ -15,32 +15,26 @@ const { getTrade, getOldTrade } = require('../services/getTrade');
...
+        const type = (trade.type === 'Buy') ? 'purchased' : 'sold';
+        const odds = parseFloat(trade.outcomeTokenMarginalPrices[trade.outcomeIndex] * 100 ).toFixed(2);
+        const tokenName = await getTokenName(web3, trade.collateralToken);
+        const decimals = await getTokenDecimals(web3, trade.collateralToken);
+        const oldTrade = await getOldTrade(trade.fpmm, trade.id, trade.creationTimestamp);
+        const amount = parseFloat(trade.collateralAmount / 10**decimals).toFixed(2);
+        if (trade.collateralAmountUSD > 1000.00) {
+            message.push('<!here>');
+        }
+        const oldOdds = oldTrade ? parseFloat(oldTrade.outcomeTokenMarginalPrices[trade.outcomeIndex] * 100 ).toFixed(2) : '0.00';
```
Comment (mariano-aguero) [inline src/events/tradeEvents.js]: Mmmm I would add `oldTrade && oldTrade.outcomeTokenMarginalPrices` as a defensive programming

File: src/events/tradeEvents.js [hunk 2]
```diff
@@ -15,32 +15,26 @@ const { getTrade, getOldTrade } = require('../services/getTrade');
...
-                            `> *Created by*: <https://omen.eth.link/#/${trade.creator}|${truncate(trade.creator, 14)}>`,
-                        );
-                        // Send Slack notification
-                        pushSlackArrayMessages(message);
-                        console.log(message.join('\n') + '\n');
-                    });
-            });
-        });
+    const trades = await getTrade(timestamp, pastTimeInSeconds, 20)
+    trades.forEach(async trade => {
```
Comment (mariano-aguero) [inline src/events/tradeEvents.js]: If you want to execute some tasks in sequence, you cannot use forEach indeed. Just use a modern [for … of loop](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Sentencias/for...of) instead, in which await will work as expected

An example
```
async function foo () {
  const elements = await doSomething()

  for (const element of elements) {
    const bar = await somethingAgain()
    console.log(bar)
  }
}
```
